### ISSUE TITLE
Fails with an unhelpful error message for Python 2.4

### ISSUE THREAD

**Issue by danjacka** [plone/plone-devstart#4]
Running plone-devstart.py on Python 2.4:

```
$ python plone-devstart.py devstarttest

Welcome to plone-devstart (version 0.2)
...

Enter a Plone version number [4.1]

* Checking for known good versions set at
  http://dist.plone.org/release/4.1/versions.cfg ...

Traceback (most recent call last):
 File "plone-devstart.py", line 449, in ?
   main()
 File "plone-devstart.py", line 242, in main
   if not check_url(kgs_url):
 File "plone-devstart.py", line 113, in check_url
   connection = httplib.HTTPConnection(split.netloc, port=split.port)
AttributeError: 'tuple' object has no attribute 'netloc'
```

[Looks like](http://docs.python.org/release/2.4/lib/module-urlparse.html) 2.4's urlparse.urlsplit returns a plain tuple with no 'netloc' or other attributes.

Would be good to fail nicely (or better yet work with Python 2.4/Plone 3). See the [related mailing list thread](http://plone.293351.n2.nabble.com/ANN-plone-devstart-please-help-test-td7361927i20.html#a7378463).
